[package]
name = "regex_rustler"
version = "0.1.0"
edition = "2021"
author = "Eyal Lampel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
colored = "2.0"
clap = { version = "4.4.11", features = ["cargo"] }
